apiVersion: v1
kind: Service
metadata:
  labels:
    role: show-guestbook
    app: nginx-frontend
  name: nginx-deploy-svc
  namespace: front
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: show-guestbook
    app: nginx-frontend
  type: LoadBalancer
